import { createServerClient } from '@supabase/ssr'
import { createClient as createSupabaseClient } from '@supabase/supabase-js'
import type { ResponseCookie } from 'next/dist/compiled/@edge-runtime/cookies'
import { cookies } from 'next/headers'

interface CookieToSet {
  name: string
  value: string
  options?: Partial<ResponseCookie>
}

// ─── Cookie-based server client ───────────────────────────────────────────────

/**
 * Server client for Server Components and Route Handlers.
 * Reads/writes the Supabase session from HTTP cookies.
 * Respects Row-Level Security via the logged-in user's JWT.
 */
export async function createClient() {
  const cookieStore = await cookies()

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll()
        },
        setAll(cookiesToSet: CookieToSet[]) {
          try {
            cookiesToSet.forEach(({ name, value, options }) => {
              cookieStore.set(name, value, options)
            })
          } catch {
            // Called from a Server Component — cookies are read-only here.
            // Session refresh is handled by middleware.
          }
        },
      },
    },
  )
}

// ─── Service role client (bypasses RLS) ──────────────────────────────────────

/**
 * Service role client for trusted server-side API operations.
 * Bypasses Row-Level Security — NEVER expose to the browser.
 *
 * Use for:
 *  - Creating/upserting users
 *  - Admin-scoped queries
 *  - Operations where the request user is already verified by middleware
 */
export function createServiceClient() {
  return createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    {
      auth: {
        persistSession:    false,
        autoRefreshToken:  false,
      },
    },
  )
}

// ─── User-scoped client (enforces RLS) ───────────────────────────────────────

/**
 * Creates a Supabase client authenticated as a specific user via a signed JWT.
 * Use this when you want DB queries to go through Row-Level Security.
 *
 * The token is generated by lib/auth/session.ts (Supabase-compatible HS256 JWT).
 */
export function createUserClient(sessionToken: string) {
  return createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      global: {
        headers: { Authorization: `Bearer ${sessionToken}` },
      },
      auth: {
        persistSession:   false,
        autoRefreshToken: false,
      },
    },
  )
}
